const suggestions = [
  // Code & Dev (100)
  "Écris une fonction pour trier un tableau par date",
  "Comment implémenter un debounce en JavaScript ?",
  "Explique les closures en JavaScript",
  "Crée un hook React pour gérer un formulaire",
  "Quelle est la différence entre REST et GraphQL ?",
  "Écris un script Python pour scraper un site web",
  "Comment fonctionne le garbage collector en Java ?",
  "Crée une API CRUD avec Express et MongoDB",
  "Explique le pattern Observer en TypeScript",
  "Comment optimiser les performances d'une app React ?",
  "Écris un algorithme de recherche binaire",
  "Quelle est la complexité de quicksort ?",
  "Comment implémenter l'authentification JWT ?",
  "Crée un composant de pagination réutilisable",
  "Explique les Web Workers et leur utilité",
  "Comment fonctionne le Virtual DOM ?",
  "Écris un middleware Express pour le rate limiting",
  "Quelle est la différence entre SQL et NoSQL ?",
  "Comment déployer une app Next.js sur Vercel ?",
  "Explique le concept de memoization",
  "Crée un système de cache avec Redis",
  "Comment gérer les erreurs en async/await ?",
  "Écris un test unitaire avec Jest",
  "Quelle est la différence entre PUT et PATCH ?",
  "Comment implémenter le lazy loading d'images ?",
  "Explique les design patterns SOLID",
  "Crée un système de notifications en temps réel",
  "Comment fonctionne WebSocket ?",
  "Écris un Dockerfile pour une app Node.js",
  "Quelle est la différence entre TCP et UDP ?",
  "Comment sécuriser une API contre les injections SQL ?",
  "Crée un système de file d'attente avec Bull",
  "Explique le concept de microservices",
  "Comment implémenter un système de retry ?",
  "Écris un parser JSON simplifié",
  "Quelle est la différence entre thread et process ?",
  "Comment fonctionne le protocole HTTP/2 ?",
  "Crée un ORM simplifié en TypeScript",
  "Explique les principes de clean architecture",
  "Comment optimiser les requêtes SQL ?",
  "Écris un algorithme de Dijkstra",
  "Quelle est la différence entre stack et heap ?",
  "Comment implémenter un pub/sub pattern ?",
  "Crée un système de migration de base de données",
  "Explique le concept de event loop en Node.js",
  "Comment fonctionne le DNS ?",
  "Écris un reverse proxy avec Nginx",
  "Quelle est la différence entre monorepo et polyrepo ?",
  "Comment implémenter le server-side rendering ?",
  "Crée un CLI tool en Node.js",
  // Science & Tech (50)
  "Explique la théorie de la relativité simplement",
  "Comment fonctionne un processeur quantique ?",
  "Quelle est la différence entre IA et machine learning ?",
  "Explique le fonctionnement d'un réseau de neurones",
  "Comment fonctionne la blockchain ?",
  "Quelle est la théorie des cordes ?",
  "Explique le principe d'incertitude de Heisenberg",
  "Comment fonctionne CRISPR ?",
  "Quelle est la différence entre fusion et fission ?",
  "Explique le concept d'entropie",
  "Comment fonctionne un satellite GPS ?",
  "Quelle est la matière noire ?",
  "Explique le paradoxe de Fermi",
  "Comment fonctionne la fibre optique ?",
  "Quelle est la théorie du Big Bang ?",
  "Explique le fonctionnement d'un laser",
  "Comment fonctionne la reconnaissance faciale ?",
  "Quelle est la différence entre AR et VR ?",
  "Explique le concept de singularité technologique",
  "Comment fonctionne un moteur électrique ?",
  "Quelle est la loi de Moore ?",
  "Explique le fonctionnement d'une batterie lithium",
  "Comment fonctionne le Wi-Fi 6 ?",
  "Quelle est la différence entre 4G et 5G ?",
  "Explique le concept de cloud computing",
  "Comment fonctionne la compression de données ?",
  "Quelle est la différence entre SSD et HDD ?",
  "Explique le fonctionnement d'un écran OLED",
  "Comment fonctionne la recharge sans fil ?",
  "Quelle est la différence entre RAM et ROM ?",
  // Créativité & Écriture (50)
  "Écris un poème sur la solitude urbaine",
  "Invente une histoire courte de science-fiction",
  "Crée un dialogue entre deux philosophes",
  "Écris une lettre de motivation percutante",
  "Invente un concept de jeu vidéo original",
  "Crée un scénario de court-métrage",
  "Écris un haïku sur la technologie",
  "Invente une recette fusion franco-japonaise",
  "Crée un pitch pour une startup",
  "Écris une critique de film constructive",
  "Invente un personnage de roman complexe",
  "Crée un plan de cours sur l'IA",
  "Écris un discours inspirant de 2 minutes",
  "Invente un concept d'application mobile",
  "Crée une métaphore pour expliquer Internet",
  "Écris un tweet viral sur la productivité",
  "Invente un exercice de créativité",
  "Crée un plan de podcast en 10 épisodes",
  "Écris une bio professionnelle originale",
  "Invente un concept de restaurant futuriste",
  "Crée un slogan pour une marque éco-responsable",
  "Écris une nouvelle en 500 mots",
  "Invente un concept de série TV",
  "Crée un plan de newsletter hebdomadaire",
  "Écris un monologue intérieur d'un robot",
  "Invente un jeu de société éducatif",
  "Crée un concept d'exposition d'art numérique",
  "Écris une chanson sur le changement climatique",
  "Invente un sport du futur",
  "Crée un concept de ville idéale",
  // Productivité & Business (50)
  "Comment structurer une journée productive ?",
  "Crée un business plan pour un SaaS",
  "Quelles sont les meilleures méthodes de gestion de projet ?",
  "Comment négocier une augmentation de salaire ?",
  "Crée un template d'email professionnel",
  "Quelles sont les tendances du marché tech 2025 ?",
  "Comment construire une marque personnelle ?",
  "Crée un plan marketing pour un lancement produit",
  "Quelles sont les erreurs courantes en freelance ?",
  "Comment automatiser des tâches répétitives ?",
  "Crée un système de prise de notes efficace",
  "Quelles sont les meilleures pratiques de remote work ?",
  "Comment préparer un entretien d'embauche tech ?",
  "Crée un tableau de bord KPI pour une startup",
  "Quelles sont les alternatives à Notion ?",
  "Comment gérer le syndrome de l'imposteur ?",
  "Crée un plan de formation en développement web",
  "Quelles sont les compétences les plus demandées en 2025 ?",
  "Comment écrire un CV qui se démarque ?",
  "Crée un workflow d'onboarding pour nouveaux employés",
  "Quelles sont les meilleures pratiques de code review ?",
  "Comment gérer un conflit en équipe ?",
  "Crée un plan de veille technologique",
  "Quelles sont les métriques importantes pour un SaaS ?",
  "Comment pitcher devant des investisseurs ?",
  "Crée un plan de croissance pour une app mobile",
  "Quelles sont les erreurs à éviter en UX design ?",
  "Comment construire une communauté en ligne ?",
  "Crée un plan de contenu pour LinkedIn",
  "Quelles sont les meilleures pratiques SEO en 2025 ?",
  // Culture & Philosophie (50)
  "Explique la philosophie stoïcienne en termes modernes",
  "Quelle est la différence entre existentialisme et nihilisme ?",
  "Résume 'Sapiens' de Yuval Noah Harari",
  "Explique le concept de surhomme chez Nietzsche",
  "Quels sont les meilleurs films de science-fiction ?",
  "Explique l'allégorie de la caverne de Platon",
  "Quelle est l'influence du Bauhaus sur le design moderne ?",
  "Résume la philosophie de Camus",
  "Quels sont les mouvements artistiques du 20e siècle ?",
  "Explique le concept de flow de Csikszentmihalyi",
  "Quelle est la différence entre éthique et morale ?",
  "Résume 'L'Art de la guerre' de Sun Tzu",
  "Explique le concept de pensée latérale",
  "Quels sont les paradoxes les plus célèbres ?",
  "Explique la théorie des jeux simplement",
  "Quelle est l'histoire de la typographie ?",
  "Résume les idées principales de Kant",
  "Explique le concept de biais cognitif",
  "Quels sont les meilleurs livres sur la créativité ?",
  "Explique la philosophie du wabi-sabi",
  "Quelle est l'histoire du mouvement open source ?",
  "Résume 'Thinking, Fast and Slow'",
  "Explique le concept d'antifragilité de Taleb",
  "Quels sont les principes du minimalisme ?",
  "Explique la différence entre corrélation et causalité",
  // Quotidien & Pratique (50)
  "Comment méditer efficacement en 10 minutes ?",
  "Quels sont les meilleurs exercices pour le dos ?",
  "Comment améliorer la qualité de son sommeil ?",
  "Quels sont les aliments les plus nutritifs ?",
  "Comment apprendre une langue rapidement ?",
  "Quels sont les meilleurs podcasts tech en français ?",
  "Comment réduire son empreinte carbone ?",
  "Quels sont les meilleurs outils de productivité gratuits ?",
  "Comment organiser un voyage au Japon ?",
  "Quels sont les bienfaits de la lecture quotidienne ?",
  "Comment commencer à investir en bourse ?",
  "Quels sont les meilleurs exercices de respiration ?",
  "Comment cuisiner un repas sain en 15 minutes ?",
  "Quels sont les meilleurs documentaires Netflix ?",
  "Comment développer sa mémoire ?",
  "Quels sont les meilleurs livres de développement personnel ?",
  "Comment organiser son espace de travail ?",
  "Quels sont les bienfaits du jeûne intermittent ?",
  "Comment apprendre à dessiner ?",
  "Quels sont les meilleurs jeux de société stratégiques ?",
  "Comment réduire le temps d'écran ?",
  "Quels sont les meilleurs thés pour la concentration ?",
  "Comment commencer le running ?",
  "Quels sont les meilleurs films d'animation japonais ?",
  "Comment faire un budget mensuel efficace ?",
  // Maths & Logique (30)
  "Explique le théorème de Bayes avec un exemple",
  "Comment fonctionne la cryptographie RSA ?",
  "Quelle est la conjecture de Goldbach ?",
  "Explique les nombres premiers de Mersenne",
  "Comment résoudre une équation différentielle ?",
  "Quelle est la suite de Fibonacci et ses applications ?",
  "Explique le concept de dimension fractale",
  "Comment fonctionne l'algorithme PageRank ?",
  "Quelle est la théorie des graphes ?",
  "Explique le problème du voyageur de commerce",
  "Comment fonctionne la transformée de Fourier ?",
  "Quelle est la différence entre P et NP ?",
  "Explique le concept de récursivité",
  "Comment fonctionne un algorithme génétique ?",
  "Quelle est la théorie de l'information de Shannon ?",
  // Design & UX (30)
  "Quels sont les principes de Gestalt en design ?",
  "Comment créer un design system cohérent ?",
  "Quelle est la différence entre UI et UX ?",
  "Comment faire un audit d'accessibilité web ?",
  "Quels sont les meilleurs outils de prototypage ?",
  "Comment choisir une palette de couleurs ?",
  "Quelle est l'importance de la typographie en web ?",
  "Comment concevoir pour le dark mode ?",
  "Quels sont les principes du responsive design ?",
  "Comment faire un test utilisateur efficace ?",
  "Quelle est la règle des 60-30-10 en design ?",
  "Comment créer des micro-interactions engageantes ?",
  "Quels sont les anti-patterns UX à éviter ?",
  "Comment designer pour l'accessibilité ?",
  "Quelle est la différence entre Material et Human Interface ?",
  // Actualités & Tendances (20)
  "Quelles sont les dernières avancées en IA ?",
  "Quel est l'état du marché crypto en ce moment ?",
  "Quelles sont les startups françaises prometteuses ?",
  "Quel est l'impact de l'IA sur l'emploi ?",
  "Quelles sont les tendances web design 2025 ?",
  "Quel est l'avenir du travail à distance ?",
  "Quelles sont les innovations en énergie renouvelable ?",
  "Quel est l'état de la course à l'espace ?",
  "Quelles sont les avancées en médecine personnalisée ?",
  "Quel est l'impact environnemental du numérique ?",
  "Quelles sont les tendances en cybersécurité ?",
  "Quel est l'avenir des véhicules autonomes ?",
  "Quelles sont les innovations en agriculture tech ?",
  "Quel est l'état de la régulation de l'IA ?",
  "Quelles sont les tendances en éducation en ligne ?",
  // Langues & Communication (20)
  "Comment améliorer son anglais professionnel ?",
  "Quelles sont les expressions idiomatiques françaises ?",
  "Comment écrire un email en anglais formel ?",
  "Quelles sont les différences entre anglais UK et US ?",
  "Comment prononcer correctement en japonais ?",
  "Quelles sont les bases de la communication non-violente ?",
  "Comment structurer une présentation orale ?",
  "Quelles sont les techniques de storytelling ?",
  "Comment écrire de manière concise ?",
  "Quelles sont les règles de la ponctuation française ?",
  "Comment traduire des expressions intraduisibles ?",
  "Quelles sont les bases du copywriting ?",
  "Comment adapter son discours à son audience ?",
  "Quelles sont les techniques de persuasion éthique ?",
  "Comment écrire un article de blog engageant ?",
  // Fun & Curiosités (30)
  "Quels sont les faits scientifiques les plus surprenants ?",
  "Raconte une anecdote historique méconnue",
  "Quels sont les records du monde les plus insolites ?",
  "Explique un concept complexe comme si j'avais 5 ans",
  "Quels sont les bugs informatiques les plus célèbres ?",
  "Raconte l'histoire d'une invention accidentelle",
  "Quels sont les animaux les plus intelligents ?",
  "Explique pourquoi le ciel est bleu",
  "Quels sont les mystères non résolus de la science ?",
  "Raconte l'histoire d'Internet en 2 minutes",
  "Quels sont les langages de programmation les plus bizarres ?",
  "Explique le paradoxe des jumeaux",
  "Quels sont les easter eggs célèbres dans les logiciels ?",
  "Raconte l'histoire de la création de Linux",
  "Quels sont les algorithmes qui gouvernent notre quotidien ?",
  "Explique comment fonctionne la mémoire humaine",
  "Quels sont les plus grands échecs technologiques ?",
  "Raconte l'histoire du premier email",
  "Quels sont les concepts mathématiques dans la nature ?",
  "Explique le concept de temps en physique",
]

export function getRandomSuggestions(count = 4): string[] {
  const shuffled = [...suggestions].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}

export { suggestions }
