// Complete translations for ru, hi, tr, nl, pl, uk
// Each language has 100% coverage of all keys

const FEAT_ITEMS_RU = [
  { title: 'Поиск в интернете в реальном времени', desc: 'Netral ищет в сети во время ответа. Источники с датами, ссылками, проверяемые.', details: ['Цитируемые источники со ссылками', 'Данные обновляются в реальном времени', 'Автоматическая перекрёстная проверка'] },
  { title: 'Продвинутые рассуждения', desc: 'Модель думает шаг за шагом, способная строго решать сложные задачи.', details: ['Структурированная цепочка мыслей', 'Многоперспективный анализ', 'Решение сложных задач'] },
  { title: 'Естественные разговоры', desc: 'Задавайте сложные вопросы, запрашивайте код, обсуждайте идеи.', details: ['Контекст сохраняется на протяжении всего разговора', 'Умная перефразировка', 'Адаптация к тону пользователя'] },
  { title: 'Сверхбыстрый стриминг', desc: 'Ответы в потоковом режиме. Читайте, пока Netral пишет.', details: ['Задержка < 200 мс', 'Потоковая передача токен за токеном', 'Можно прервать в любой момент'] },
  { title: 'Генерация кода', desc: 'Python, TypeScript, Rust, SQL… Чистый, прокомментированный, рабочий код.', details: ['Подсветка синтаксиса', 'Объяснение строка за строкой', 'Автоматическое определение языка'] },
  { title: 'Семантический поиск', desc: 'Понимает смысл, а не только ключевые слова. Находит то, что вам действительно нужно.', details: ['Контекстуальное понимание', 'Релевантные результаты', 'Умная фильтрация шума'] },
  { title: 'Приватность по умолчанию', desc: 'Зашифрованные сессии. Данные можно удалить в любой момент.', details: ['Сквозное шифрование', 'Мгновенное удаление', 'Без хранения данных'] },
  { title: 'Мультиформат', desc: 'Текст, таблицы, списки, код, математика. Адаптируется к наиболее понятному формату.', details: ['Расширенный Markdown', 'Таблицы и графики', 'Формулы LaTeX'] },
]


const FEAT_ITEMS_HI = [
  { title: 'रियल-टाइम वेब खोज', desc: 'Netral जवाब देते समय वेब खोजता है। दिनांकित, क्लिक योग्य, सत्यापन योग्य स्रोत।', details: ['लिंक के साथ उद्धृत स्रोत', 'रियल-टाइम में अपडेट किया गया डेटा', 'स्वचालित क्रॉस-सत्यापन'] },
  { title: 'उन्नत तर्क', desc: 'एक मॉडल जो कदम-दर-कदम सोचता है, जटिल समस्याओं को कठोरता से हल करने में सक्षम।', details: ['संरचित विचार श्रृंखला', 'बहु-दृष्टिकोण विश्लेषण', 'जटिल समस्या समाधान'] },
  { title: 'प्राकृतिक बातचीत', desc: 'जटिल प्रश्न पूछें, कोड मांगें, विचारों पर बहस करें।', details: ['पूरी बातचीत में संदर्भ बनाए रखा', 'बुद्धिमान पुनः-निर्माण', 'उपयोगकर्ता के स्वर के अनुकूल'] },
  { title: 'अल्ट्रा-फास्ट स्ट्रीमिंग', desc: 'स्ट्रीमिंग जवाब। Netral लिखते समय पढ़ें।', details: ['लेटेंसी < 200ms', 'टोकन-दर-टोकन स्ट्रीमिंग', 'किसी भी समय बाधित करने योग्य'] },
  { title: 'कोड जनरेशन', desc: 'Python, TypeScript, Rust, SQL… साफ, टिप्पणी वाला, कार्यात्मक कोड।', details: ['सिंटैक्स हाइलाइटिंग', 'लाइन-दर-लाइन स्पष्टीकरण', 'स्वचालित भाषा पहचान'] },
  { title: 'सिमेंटिक खोज', desc: 'केवल कीवर्ड नहीं, अर्थ समझता है। आपको वास्तव में जो चाहिए वह खोजता है।', details: ['संदर्भात्मक समझ', 'प्रासंगिक परिणाम', 'बुद्धिमान शोर फ़िल्टरिंग'] },
  { title: 'डिफ़ॉल्ट रूप से निजी', desc: 'एन्क्रिप्टेड सत्र। कभी भी डेटा हटाने योग्य।', details: ['एंड-टू-एंड एन्क्रिप्शन', 'तत्काल हटाना', 'कोई डेटा प्रतिधारण नहीं'] },
  { title: 'मल्टी-फॉर्मेट', desc: 'टेक्स्ट, टेबल, सूचियां, कोड, गणित। सबसे स्पष्ट प्रारूप के अनुकूल।', details: ['समृद्ध Markdown', 'टेबल और चार्ट', 'LaTeX फ़ॉर्मूले'] },
]


const FEAT_ITEMS_TR = [
  { title: 'Gerçek zamanlı web araması', desc: 'Netral yanıt verirken web\'de arama yapar. Tarihli, tıklanabilir, doğrulanabilir kaynaklar.', details: ['Bağlantılı alıntı kaynaklar', 'Gerçek zamanlı güncellenen veriler', 'Otomatik çapraz doğrulama'] },
  { title: 'Gelişmiş muhakeme', desc: 'Adım adım düşünen, karmaşık sorunları titizlikle çözebilen bir model.', details: ['Yapılandırılmış düşünce zinciri', 'Çok perspektifli analiz', 'Karmaşık problem çözme'] },
  { title: 'Doğal konuşmalar', desc: 'Karmaşık sorular sorun, kod isteyin, fikirleri tartışın.', details: ['Bağlam boyunca korunur', 'Akıllı yeniden ifade', 'Kullanıcı tonuna uyum'] },
  { title: 'Ultra hızlı akış', desc: 'Akış yanıtları. Netral yazarken okuyun.', details: ['Gecikme < 200ms', 'Jeton jeton akış', 'İstediğiniz zaman kesilebilir'] },
  { title: 'Kod üretimi', desc: 'Python, TypeScript, Rust, SQL… Temiz, yorumlu, işlevsel kod.', details: ['Sözdizimi vurgulama', 'Satır satır açıklama', 'Otomatik dil tespiti'] },
  { title: 'Anlamsal arama', desc: 'Yalnızca anahtar kelimeleri değil, anlamı anlar. Gerçekten ihtiyacınız olanı bulur.', details: ['Bağlamsal anlama', 'İlgili sonuçlar', 'Akıllı gürültü filtreleme'] },
  { title: 'Varsayılan olarak gizli', desc: 'Şifreli oturumlar. Veriler istediğiniz zaman silinebilir.', details: ['Uçtan uca şifreleme', 'Anında silme', 'Veri saklama yok'] },
  { title: 'Çoklu format', desc: 'Metin, tablolar, listeler, kod, matematik. En açık formata uyum sağlar.', details: ['Zengin Markdown', 'Tablolar ve grafikler', 'LaTeX formülleri'] },
]

const FEAT_ITEMS_NL = [
  { title: 'Realtime web zoeken', desc: 'Netral zoekt op het web terwijl het antwoordt. Gedateerde, klikbare, verifieerbare bronnen.', details: ['Geciteerde bronnen met links', 'Realtime bijgewerkte gegevens', 'Automatische kruisverificatie'] },
  { title: 'Geavanceerd redeneren', desc: 'Een model dat stap voor stap denkt en complexe problemen rigoureus kan oplossen.', details: ['Gestructureerde gedachtenketen', 'Multi-perspectief analyse', 'Complexe probleemoplossing'] },
  { title: 'Natuurlijke gesprekken', desc: 'Stel complexe vragen, vraag om code, debatteer over ideeën.', details: ['Context door het gesprek behouden', 'Intelligente herformulering', 'Aanpassing aan gebruikerstoon'] },
  { title: 'Ultra-snel streamen', desc: 'Streaming antwoorden. Lees terwijl Netral schrijft.', details: ['Latentie < 200ms', 'Token-voor-token streaming', 'Op elk moment te onderbreken'] },
  { title: 'Codegeneratie', desc: 'Python, TypeScript, Rust, SQL… Schone, gecommentarieerde, functionele code.', details: ['Syntaxisaccentuering', 'Regel-voor-regel uitleg', 'Automatische taaldetectie'] },
  { title: 'Semantisch zoeken', desc: 'Begrijpt betekenis, niet alleen zoekwoorden. Vindt wat u echt nodig heeft.', details: ['Contextueel begrip', 'Relevante resultaten', 'Intelligente ruisfiltering'] },
  { title: 'Standaard privé', desc: 'Versleutelde sessies. Gegevens op elk moment te verwijderen.', details: ['End-to-end versleuteling', 'Onmiddellijke verwijdering', 'Geen gegevensretentie'] },
  { title: 'Multi-formaat', desc: 'Tekst, tabellen, lijsten, code, wiskunde. Past zich aan het duidelijkste formaat aan.', details: ['Rijke Markdown', 'Tabellen en grafieken', 'LaTeX-formules'] },
]


const FEAT_ITEMS_PL = [
  { title: 'Wyszukiwanie w sieci w czasie rzeczywistym', desc: 'Netral przeszukuje sieć podczas odpowiadania. Datowane, klikalne, weryfikowalne źródła.', details: ['Cytowane źródła z linkami', 'Dane aktualizowane w czasie rzeczywistym', 'Automatyczna weryfikacja krzyżowa'] },
  { title: 'Zaawansowane rozumowanie', desc: 'Model myślący krok po kroku, zdolny do rygorystycznego rozwiązywania złożonych problemów.', details: ['Ustrukturyzowany łańcuch myśli', 'Analiza wieloperspektywiczna', 'Rozwiązywanie złożonych problemów'] },
  { title: 'Naturalne rozmowy', desc: 'Zadawaj złożone pytania, proś o kod, dyskutuj o pomysłach.', details: ['Kontekst zachowany przez całą rozmowę', 'Inteligentne przeformułowanie', 'Dostosowanie do tonu użytkownika'] },
  { title: 'Ultrabłyskawiczny streaming', desc: 'Odpowiedzi strumieniowe. Czytaj, gdy Netral pisze.', details: ['Opóźnienie < 200ms', 'Strumieniowanie token po tokenie', 'Możliwość przerwania w dowolnym momencie'] },
  { title: 'Generowanie kodu', desc: 'Python, TypeScript, Rust, SQL… Czysty, skomentowany, funkcjonalny kod.', details: ['Podświetlanie składni', 'Wyjaśnienie wiersz po wierszu', 'Automatyczne wykrywanie języka'] },
  { title: 'Wyszukiwanie semantyczne', desc: 'Rozumie znaczenie, nie tylko słowa kluczowe. Znajduje to, czego naprawdę potrzebujesz.', details: ['Zrozumienie kontekstowe', 'Trafne wyniki', 'Inteligentne filtrowanie szumu'] },
  { title: 'Prywatność domyślnie', desc: 'Zaszyfrowane sesje. Dane do usunięcia w dowolnym momencie.', details: ['Szyfrowanie end-to-end', 'Natychmiastowe usuwanie', 'Brak przechowywania danych'] },
  { title: 'Wieloformatowy', desc: 'Tekst, tabele, listy, kod, matematyka. Dostosowuje się do najczytelniejszego formatu.', details: ['Bogaty Markdown', 'Tabele i wykresy', 'Wzory LaTeX'] },
]

const FEAT_ITEMS_UK = [
  { title: 'Пошук в інтернеті в реальному часі', desc: 'Netral шукає в мережі під час відповіді. Джерела з датами, посиланнями, перевіряються.', details: ['Цитовані джерела з посиланнями', 'Дані оновлюються в реальному часі', 'Автоматична перехресна перевірка'] },
  { title: 'Розширені міркування', desc: 'Модель мислить крок за кроком, здатна суворо вирішувати складні задачі.', details: ['Структурований ланцюжок думок', 'Багатоперспективний аналіз', 'Вирішення складних задач'] },
  { title: 'Природні розмови', desc: 'Ставте складні питання, запитуйте код, обговорюйте ідеї.', details: ['Контекст зберігається протягом усієї розмови', 'Розумне перефразування', 'Адаптація до тону користувача'] },
  { title: 'Надшвидкий стрімінг', desc: 'Потокові відповіді. Читайте, поки Netral пише.', details: ['Затримка < 200 мс', 'Потокова передача токен за токеном', 'Можна перервати в будь-який момент'] },
  { title: 'Генерація коду', desc: 'Python, TypeScript, Rust, SQL… Чистий, з коментарями, робочий код.', details: ['Підсвічування синтаксису', 'Пояснення рядок за рядком', 'Автоматичне визначення мови'] },
  { title: 'Семантичний пошук', desc: 'Розуміє зміст, а не лише ключові слова. Знаходить те, що вам дійсно потрібно.', details: ['Контекстуальне розуміння', 'Релевантні результати', 'Розумна фільтрація шуму'] },
  { title: 'Приватність за замовчуванням', desc: 'Зашифровані сесії. Дані можна видалити в будь-який момент.', details: ['Наскрізне шифрування', 'Миттєве видалення', 'Без зберігання даних'] },
  { title: 'Мультиформат', desc: 'Текст, таблиці, списки, код, математика. Адаптується до найзрозумілішого формату.', details: ['Розширений Markdown', 'Таблиці та графіки', 'Формули LaTeX'] },
]


export const extraTranslations: Record<string, any> = {
  ru: {
    nav: { features: 'Функции', pricing: 'Цены', login: 'Войти', start: 'Начать' },
    hero: { badge: 'Netral 1.3 — Улучшенный поиск в интернете', title1: 'ИИ, который ищет', title2: 'прежде чем ответить.', subtitle: 'Задайте вопрос. Netral ищет в интернете, анализирует источники и даёт точный ответ с проверяемыми ссылками.', cta: 'Начать бесплатно', login: 'Войти', note: 'Бесплатно • Без карты • Готово за 10 секунд' },
    demo: { userMsg: 'Какие последние разработки в ИИ на этой неделе?', searching: 'Поиск…', response1: 'Вот основные достижения этой недели:', response2: '— улучшенное многошаговое рассуждение.', response3: '— более стабильные автономные агенты' },
    stats: { latency: 'Средняя задержка', uptime: 'Доступность', users: 'Активные пользователи' },
    features: { title: 'Создано для любопытных умов', subtitle: 'ИИ, который не выдумывает. Знает, когда искать. Цитирует источники.', seeAll: 'Все функции →', items: [{ title: 'Поиск в реальном времени', desc: 'Источники с датами, кликабельные, проверяемые.' }, { title: 'Продвинутые рассуждения', desc: 'Пошаговое решение сложных задач.' }, { title: 'Естественные разговоры', desc: 'Как разговор с надёжным экспертом.' }, { title: 'Мгновенный стриминг', desc: 'Читайте ответ по мере его формирования.' }, { title: 'Семантический поиск', desc: 'Понимает смысл, не только ключевые слова.' }, { title: 'Приватность по умолчанию', desc: 'Зашифровано. Удаляемо. Никогда не используется для обучения.' }] },
    pricing: { title1: 'Бесплатно для старта.', title2: 'Pro когда будете готовы.', subtitle: '20 сообщений/день бесплатно. Pro для безлимитного доступа за 12€/месяц.', cta: 'Создать бесплатный аккаунт', seePricing: 'Посмотреть цены' },
    footer: { privacy: 'Конфиденциальность', contact: 'Контакты' },
    chat: { hello: 'Привет', helloName: 'Привет, {name}', howCanIHelp: 'Чем могу помочь сегодня?', newConversation: 'Новый разговор', search: 'Поиск', noConversations: 'Нет разговоров', noResults: 'Нет результатов', today: 'Сегодня', yesterday: 'Вчера', last7days: 'Последние 7 дней', last30days: 'Последние 30 дней', older: 'Старше', settings: 'Настройки', logout: 'Выйти', rename: 'Переименовать', remix: 'Ремикс', delete: 'Удалить', deleteConfirm: 'Удалить этот разговор?', searching: 'Поиск…', reading: 'Чтение источников…', thinking: 'Размышление…', login: 'Войти', loginTitle: 'Добро пожаловать', loginSubtitle: 'Войдите в аккаунт', signupTitle: 'Создать аккаунт', signupSubtitle: 'Бесплатно, менее минуты', noAccount: 'Нет аккаунта?', createOne: 'Создать', alreadyAccount: 'Уже зарегистрированы?', signIn: 'Войти', createAccount: 'Создать аккаунт' },
    vscodeAuth: { title: 'Netral Code', subtitle: 'Подключите IDE к Netral', loginRequired: 'Требуется вход', loginDesc: 'Войдите, чтобы связать аккаунт с VS Code.', confirmTitle: 'Связать VS Code', confirmDesc: 'Разрешить Netral Code доступ к аккаунту?', authorize: 'Авторизовать', tokenNote: 'Будет создан API-токен для расширения VS Code.', success: 'Подключено!', successDesc: 'Вернитесь в VS Code. Расширение готово.', expired: 'Код истёк', expiredDesc: 'Введите /login в VS Code для повтора.', error: 'Ошибка' },
    featuresPage: { back: 'Назад', title: 'Функции', subtitle: 'Всё необходимое для надёжного, быстрого и конфиденциального ИИ.', cta: 'Готовы попробовать?', ctaDesc: 'Создайте аккаунт за 10 секунд. Бесплатно, без карты.', ctaBtn: 'Начать бесплатно', items: FEAT_ITEMS_RU },
    pricingPage: { back: 'Назад', title1: 'Простые цены,', title2: 'без сюрпризов.', subtitle: 'Начните бесплатно. Перейдите на Pro, когда будете готовы.', popular: 'Популярный', faqTitle: 'Часто задаваемые вопросы', plans: [{ name: 'Бесплатно', price: '0€', period: '/месяц', desc: 'Откройте для себя Netral без обязательств.', cta: 'Начать', features: ['20 сообщений в день', 'Базовый поиск в интернете', 'История 7 дней', '1 одновременный разговор'] }, { name: 'Pro', price: '12€', period: '/месяц', desc: 'Для профессионалов и творческих людей.', cta: 'Перейти на Pro', features: ['Безлимитные сообщения', 'Расширенный поиск', 'Безлимитная история', 'Безлимитные разговоры', 'Приоритетная модель (GPT-4o)', 'Экспорт разговоров', 'Приоритетная поддержка'] }, { name: 'Команда', price: '29€', period: '/пользователь/месяц', desc: 'Для команд, желающих сотрудничать.', cta: 'Связаться', features: ['Всё из Pro', 'Общее рабочее пространство', 'Управление участниками', 'API доступ', 'SSO & SAML', 'SLA 99.9%', 'Выделенный менеджер'] }], faq: [{ q: 'Можно ли отменить в любое время?', a: 'Да. Без обязательств. Отмените в один клик из настроек.' }, { q: 'Мои данные в безопасности?', a: 'Абсолютно. Сквозное шифрование, без хранения после удаления.' }, { q: 'Есть ли лимит сообщений в Pro?', a: 'Нет. Сообщения в Pro безлимитны.' }] },
  },


  hi: {
    nav: { features: 'सुविधाएँ', pricing: 'मूल्य', login: 'लॉगिन', start: 'शुरू करें' },
    hero: { badge: 'Netral 1.3 — बेहतर वेब खोज', title1: 'AI जो खोजता है', title2: 'जवाब देने से पहले।', subtitle: 'एक सवाल पूछें। Netral वेब खोजता है, स्रोतों का विश्लेषण करता है, और सत्यापन योग्य उद्धरणों के साथ सटीक जवाब देता है।', cta: 'मुफ्त शुरू करें', login: 'लॉगिन', note: 'मुफ्त • कोई कार्ड नहीं • 10 सेकंड में तैयार' },
    demo: { userMsg: 'इस हफ्ते AI के क्षेत्र में नवीनतम विकास क्या हैं?', searching: 'खोज रहा है…', response1: 'इस सप्ताह के प्रमुख विकास यहां हैं:', response2: '— बेहतर बहु-चरण तर्क।', response3: '— अधिक स्थिर स्वायत्त एजेंट' },
    stats: { latency: 'औसत विलंबता', uptime: 'उपलब्धता', users: 'सक्रिय उपयोगकर्ता' },
    features: { title: 'जिज्ञासु मनों के लिए बनाया गया', subtitle: 'एक AI जो गढ़ता नहीं। जानता है कब खोजना है। अपने स्रोतों का हवाला देता है।', seeAll: 'सभी सुविधाएँ देखें →', items: [{ title: 'रियल-टाइम वेब खोज', desc: 'दिनांकित, क्लिक योग्य, सत्यापन योग्य स्रोत।' }, { title: 'उन्नत तर्क', desc: 'जटिल समस्याओं का कदम-दर-कदम समाधान।' }, { title: 'प्राकृतिक बातचीत', desc: 'किसी विश्वसनीय विशेषज्ञ से बात करने जैसा।' }, { title: 'तात्कालिक स्ट्रीमिंग', desc: 'जवाब बनते समय पढ़ें।' }, { title: 'सिमेंटिक खोज', desc: 'केवल कीवर्ड नहीं, अर्थ समझता है।' }, { title: 'डिफ़ॉल्ट रूप से निजी', desc: 'एन्क्रिप्टेड। मिटाने योग्य। कभी प्रशिक्षण के लिए उपयोग नहीं।' }] },
    pricing: { title1: 'शुरू करने के लिए मुफ्त।', title2: 'Pro जब तैयार हों।', subtitle: '20 संदेश/दिन मुफ्त। Pro के लिए असीमित पहुंच 12€/माह।', cta: 'मुफ्त खाता बनाएं', seePricing: 'मूल्य देखें' },
    footer: { privacy: 'गोपनीयता', contact: 'संपर्क' },
    chat: { hello: 'नमस्ते', helloName: 'नमस्ते, {name}', howCanIHelp: 'आज मैं आपकी कैसे मदद कर सकता हूँ?', newConversation: 'नई बातचीत', search: 'खोजें', noConversations: 'कोई बातचीत नहीं', noResults: 'कोई परिणाम नहीं', today: 'आज', yesterday: 'कल', last7days: 'पिछले 7 दिन', last30days: 'पिछले 30 दिन', older: 'पुराना', settings: 'सेटिंग्स', logout: 'लॉगआउट', rename: 'नाम बदलें', remix: 'रीमिक्स', delete: 'हटाएं', deleteConfirm: 'यह बातचीत हटाएं?', searching: 'खोज रहा है…', reading: 'स्रोत पढ़ रहा है…', thinking: 'सोच रहा है…', login: 'लॉगिन', loginTitle: 'स्वागत है', loginSubtitle: 'अपने खाते में लॉगिन करें', signupTitle: 'खाता बनाएं', signupSubtitle: 'मुफ्त, एक मिनट से कम', noAccount: 'खाता नहीं है?', createOne: 'बनाएं', alreadyAccount: 'पहले से पंजीकृत?', signIn: 'लॉगिन', createAccount: 'खाता बनाएं' },
    vscodeAuth: { title: 'Netral Code', subtitle: 'अपने IDE को Netral से जोड़ें', loginRequired: 'लॉगिन आवश्यक', loginDesc: 'अपने खाते को VS Code से लिंक करने के लिए लॉगिन करें।', confirmTitle: 'VS Code लिंक करें', confirmDesc: 'Netral Code को आपके खाते तक पहुंचने की अनुमति दें?', authorize: 'अनुमति दें', tokenNote: 'VS Code एक्सटेंशन के लिए API टोकन बनाया जाएगा।', success: 'जुड़ गया!', successDesc: 'VS Code पर वापस जाएं। एक्सटेंशन तैयार है।', expired: 'कोड समाप्त', expiredDesc: 'VS Code में /login टाइप करें।', error: 'त्रुटि' },
    featuresPage: { back: 'वापस', title: 'सुविधाएँ', subtitle: 'एक विश्वसनीय, तेज़ और गोपनीयता-सम्मानजनक AI के लिए सब कुछ।', cta: 'आज़माने के लिए तैयार?', ctaDesc: '10 सेकंड में खाता बनाएं। मुफ्त, कोई कार्ड नहीं।', ctaBtn: 'मुफ्त शुरू करें', items: FEAT_ITEMS_HI },
    pricingPage: { back: 'वापस', title1: 'सरल मूल्य,', title2: 'कोई आश्चर्य नहीं।', subtitle: 'मुफ्त शुरू करें। तैयार होने पर Pro में अपग्रेड करें।', popular: 'लोकप्रिय', faqTitle: 'अक्सर पूछे जाने वाले प्रश्न', plans: [{ name: 'मुफ्त', price: '0€', period: '/माह', desc: 'बिना प्रतिबद्धता के Netral खोजें।', cta: 'शुरू करें', features: ['प्रति दिन 20 संदेश', 'बुनियादी वेब खोज', '7 दिन का इतिहास', '1 एक साथ बातचीत'] }, { name: 'Pro', price: '12€', period: '/माह', desc: 'पेशेवरों और रचनाकारों के लिए।', cta: 'Pro में जाएं', features: ['असीमित संदेश', 'उन्नत वेब खोज', 'असीमित इतिहास', 'असीमित बातचीत', 'प्राथमिकता मॉडल (GPT-4o)', 'बातचीत निर्यात', 'प्राथमिकता सहायता'] }, { name: 'टीम', price: '29€', period: '/उपयोगकर्ता/माह', desc: 'सहयोग करने वाली टीमों के लिए।', cta: 'संपर्क करें', features: ['Pro सब कुछ शामिल', 'साझा कार्यक्षेत्र', 'सदस्य प्रबंधन', 'API पहुंच', 'SSO & SAML', 'SLA 99.9%', 'समर्पित अकाउंट मैनेजर'] }], faq: [{ q: 'क्या मैं कभी भी रद्द कर सकता हूं?', a: 'हां। कोई प्रतिबद्धता नहीं। सेटिंग्स से एक क्लिक में रद्द करें।' }, { q: 'क्या मेरा डेटा सुरक्षित है?', a: 'बिल्कुल। एंड-टू-एंड एन्क्रिप्शन, हटाने के बाद कोई प्रतिधारण नहीं।' }, { q: 'क्या Pro में संदेश सीमा है?', a: 'नहीं। Pro में संदेश असीमित हैं।' }] },
  },


  tr: {
    nav: { features: 'Özellikler', pricing: 'Fiyatlar', login: 'Giriş', start: 'Başla' },
    hero: { badge: 'Netral 1.3 — Geliştirilmiş web araması', title1: 'Cevaplamadan önce', title2: 'arayan yapay zeka.', subtitle: 'Bir soru sorun. Netral web\'de arama yapar, kaynakları analiz eder ve doğrulanabilir alıntılarla kesin bir yanıt verir.', cta: 'Ücretsiz başla', login: 'Giriş', note: 'Ücretsiz • Kart gerekmez • 10 saniyede hazır' },
    demo: { userMsg: 'Bu hafta yapay zekadaki son gelişmeler neler?', searching: 'Aranıyor…', response1: 'Bu haftanın başlıca gelişmeleri:', response2: '— geliştirilmiş çok adımlı akıl yürütme.', response3: '— daha kararlı otonom ajanlar' },
    stats: { latency: 'Ortalama gecikme', uptime: 'Çalışma süresi', users: 'Aktif kullanıcılar' },
    features: { title: 'Meraklı zihinler için inşa edildi', subtitle: 'Uydurmayan bir yapay zeka. Ne zaman araması gerektiğini bilen. Kaynaklarını aktaran.', seeAll: 'Tüm özellikleri gör →', items: [{ title: 'Gerçek zamanlı web araması', desc: 'Tarihli, tıklanabilir, doğrulanabilir kaynaklar.' }, { title: 'Gelişmiş muhakeme', desc: 'Karmaşık sorunların adım adım çözümü.' }, { title: 'Doğal konuşmalar', desc: 'Güvenilir bir uzmanla konuşmak gibi.' }, { title: 'Anında akış', desc: 'Yanıt oluşurken okuyun.' }, { title: 'Anlamsal arama', desc: 'Yalnızca anahtar kelimeleri değil, anlamı anlar.' }, { title: 'Varsayılan olarak gizli', desc: 'Şifreli. Silinebilir. Eğitim için asla kullanılmaz.' }] },
    pricing: { title1: 'Başlamak için ücretsiz.', title2: 'Hazır olduğunuzda Pro.', subtitle: 'Günde 20 mesaj ücretsiz. Sınırsız erişim için Pro\'ya geçin, 12€/ay.', cta: 'Ücretsiz hesap oluştur', seePricing: 'Fiyatları gör' },
    footer: { privacy: 'Gizlilik', contact: 'İletişim' },
    chat: { hello: 'Merhaba', helloName: 'Merhaba, {name}', howCanIHelp: 'Bugün size nasıl yardımcı olabilirim?', newConversation: 'Yeni konuşma', search: 'Ara', noConversations: 'Konuşma yok', noResults: 'Sonuç yok', today: 'Bugün', yesterday: 'Dün', last7days: 'Son 7 gün', last30days: 'Son 30 gün', older: 'Daha eski', settings: 'Ayarlar', logout: 'Çıkış yap', rename: 'Yeniden adlandır', remix: 'Remix', delete: 'Sil', deleteConfirm: 'Bu konuşma silinsin mi?', searching: 'Aranıyor…', reading: 'Kaynaklar okunuyor…', thinking: 'Düşünüyor…', login: 'Giriş', loginTitle: 'Hoş geldiniz', loginSubtitle: 'Hesabınıza giriş yapın', signupTitle: 'Hesap oluştur', signupSubtitle: 'Ücretsiz, bir dakikadan az', noAccount: 'Hesabınız yok mu?', createOne: 'Oluştur', alreadyAccount: 'Zaten kayıtlı mısınız?', signIn: 'Giriş yap', createAccount: 'Hesabımı oluştur' },
    vscodeAuth: { title: 'Netral Code', subtitle: 'IDE\'nizi Netral\'a bağlayın', loginRequired: 'Giriş gerekli', loginDesc: 'Hesabınızı VS Code\'a bağlamak için giriş yapın.', confirmTitle: 'VS Code\'u Bağla', confirmDesc: 'Netral Code\'un hesabınıza erişmesine izin verilsin mi?', authorize: 'Yetkilendir', tokenNote: 'VS Code uzantısı için bir API token oluşturulacak.', success: 'Bağlandı!', successDesc: 'VS Code\'a geri dönün. Uzantı hazır.', expired: 'Kod süresi doldu', expiredDesc: 'Yeniden denemek için VS Code\'a /login yazın.', error: 'Hata' },
    featuresPage: { back: 'Geri', title: 'Özellikler', subtitle: 'Güvenilir, hızlı ve gizliliğe saygılı bir yapay zeka için ihtiyacınız olan her şey.', cta: 'Denemeye hazır mısınız?', ctaDesc: '10 saniyede hesap oluşturun. Ücretsiz, kart gerekmez.', ctaBtn: 'Ücretsiz başla', items: FEAT_ITEMS_TR },
    pricingPage: { back: 'Geri', title1: 'Basit fiyatlar,', title2: 'sürpriz yok.', subtitle: 'Ücretsiz başlayın. Hazır olduğunuzda Pro\'ya geçin.', popular: 'Popüler', faqTitle: 'Sık sorulan sorular', plans: [{ name: 'Ücretsiz', price: '0€', period: '/ay', desc: 'Netral\'ı taahhütsüz keşfedin.', cta: 'Başla', features: ['Günde 20 mesaj', 'Temel web araması', '7 günlük geçmiş', '1 eş zamanlı konuşma'] }, { name: 'Pro', price: '12€', period: '/ay', desc: 'Profesyoneller ve yaratıcılar için.', cta: 'Pro\'ya geç', features: ['Sınırsız mesaj', 'Gelişmiş web araması', 'Sınırsız geçmiş', 'Sınırsız konuşma', 'Öncelikli model (GPT-4o)', 'Konuşma dışa aktarma', 'Öncelikli destek'] }, { name: 'Takım', price: '29€', period: '/kullanıcı/ay', desc: 'İşbirliği yapmak isteyen takımlar için.', cta: 'İletişime geç', features: ['Pro\'nun tümü dahil', 'Paylaşılan çalışma alanı', 'Üye yönetimi', 'API erişimi', 'SSO & SAML', 'SLA 99.9%', 'Özel hesap yöneticisi'] }], faq: [{ q: 'İstediğim zaman iptal edebilir miyim?', a: 'Evet. Taahhüt yok. Ayarlardan tek tıkla iptal edin.' }, { q: 'Verilerim güvende mi?', a: 'Kesinlikle. Uçtan uca şifreleme, silme sonrası saklama yok.' }, { q: 'Pro\'da mesaj sınırı var mı?', a: 'Hayır. Pro\'da mesajlar sınırsız.' }] },
  },
  nl: {
    nav: { features: 'Functies', pricing: 'Prijzen', login: 'Inloggen', start: 'Starten' },
    hero: { badge: 'Netral 1.3 — Verbeterde webzoekopdracht', title1: 'De AI die zoekt', title2: 'voordat hij antwoordt.', subtitle: 'Stel een vraag. Netral doorzoekt het web, analyseert bronnen en geeft je een nauwkeurig antwoord met verifieerbare citaten.', cta: 'Gratis beginnen', login: 'Inloggen', note: 'Gratis • Geen creditcard • Klaar in 10 seconden' },
    demo: { userMsg: 'Wat zijn de laatste AI-ontwikkelingen van deze week?', searching: 'Zoeken…', response1: 'Dit zijn de belangrijkste vooruitgangen van deze week:', response2: '— verbeterd redeneren in meerdere stappen.', response3: '— stabielere autonome agenten' },
    stats: { latency: 'Gemiddelde latentie', uptime: 'Beschikbaarheid', users: 'Actieve gebruikers' },
    features: { title: 'Gebouwd voor nieuwsgierige geesten', subtitle: 'Een AI die niets verzint. Die weet wanneer te zoeken. Die zijn bronnen citeert.', seeAll: 'Alle functies bekijken →', items: [{ title: 'Realtime webzoekopdracht', desc: 'Gedateerde, klikbare, verifieerbare bronnen.' }, { title: 'Geavanceerd redeneren', desc: 'Stapsgewijs oplossen van complexe problemen.' }, { title: 'Natuurlijke gesprekken', desc: 'Zoals praten met een vertrouwde expert.' }, { title: 'Direct streamen', desc: 'Lees het antwoord terwijl het wordt gevormd.' }, { title: 'Semantisch zoeken', desc: 'Begrijpt betekenis, niet alleen zoekwoorden.' }, { title: 'Standaard privé', desc: 'Versleuteld. Verwijderbaar. Nooit gebruikt voor training.' }] },
    pricing: { title1: 'Gratis beginnen.', title2: 'Pro wanneer je klaar bent.', subtitle: '20 berichten/dag gratis. Upgrade naar Pro voor onbeperkte toegang voor 12€/maand.', cta: 'Gratis account aanmaken', seePricing: 'Prijzen bekijken' },
    footer: { privacy: 'Privacy', contact: 'Contact' },
    chat: { hello: 'Hallo', helloName: 'Hallo, {name}', howCanIHelp: 'Hoe kan ik je vandaag helpen?', newConversation: 'Nieuw gesprek', search: 'Zoeken', noConversations: 'Geen gesprekken', noResults: 'Geen resultaten', today: 'Vandaag', yesterday: 'Gisteren', last7days: 'Laatste 7 dagen', last30days: 'Laatste 30 dagen', older: 'Ouder', settings: 'Instellingen', logout: 'Uitloggen', rename: 'Hernoemen', remix: 'Remix', delete: 'Verwijderen', deleteConfirm: 'Dit gesprek verwijderen?', searching: 'Zoeken…', reading: 'Bronnen lezen…', thinking: 'Nadenken…', login: 'Inloggen', loginTitle: 'Welkom terug', loginSubtitle: 'Log in op je account', signupTitle: 'Account aanmaken', signupSubtitle: 'Gratis, in minder dan een minuut', noAccount: 'Geen account?', createOne: 'Aanmaken', alreadyAccount: 'Al geregistreerd?', signIn: 'Inloggen', createAccount: 'Mijn account aanmaken' },
    vscodeAuth: { title: 'Netral Code', subtitle: 'Verbind je IDE met Netral', loginRequired: 'Inloggen vereist', loginDesc: 'Log in om je account te koppelen aan VS Code.', confirmTitle: 'VS Code koppelen', confirmDesc: 'Netral Code toegang geven tot je account?', authorize: 'Autoriseren', tokenNote: 'Er wordt een API-token aangemaakt voor de VS Code-extensie.', success: 'Verbonden!', successDesc: 'Ga terug naar VS Code. De extensie is klaar.', expired: 'Code verlopen', expiredDesc: 'Typ /login in VS Code om opnieuw te proberen.', error: 'Fout' },
    featuresPage: { back: 'Terug', title: 'Functies', subtitle: 'Alles wat je nodig hebt voor een betrouwbare, snelle en privacyvriendelijke AI.', cta: 'Klaar om te proberen?', ctaDesc: 'Maak in 10 seconden een account. Gratis, geen kaart.', ctaBtn: 'Gratis beginnen', items: FEAT_ITEMS_NL },
    pricingPage: { back: 'Terug', title1: 'Eenvoudige prijzen,', title2: 'geen verrassingen.', subtitle: 'Begin gratis. Upgrade naar Pro wanneer je klaar bent.', popular: 'Populair', faqTitle: 'Veelgestelde vragen', plans: [{ name: 'Gratis', price: '€0', period: '/maand', desc: 'Ontdek Netral zonder verplichting.', cta: 'Beginnen', features: ['20 berichten per dag', 'Basis webzoekopdracht', '7 dagen geschiedenis', '1 gelijktijdig gesprek'] }, { name: 'Pro', price: '€12', period: '/maand', desc: 'Voor professionals en creatievelingen.', cta: 'Naar Pro', features: ['Onbeperkte berichten', 'Geavanceerd zoeken', 'Onbeperkte geschiedenis', 'Onbeperkte gesprekken', 'Prioriteitsmodel (GPT-4o)', 'Gesprekken exporteren', 'Prioriteitsondersteuning'] }, { name: 'Team', price: '€29', period: '/gebruiker/maand', desc: 'Voor teams die willen samenwerken.', cta: 'Neem contact op', features: ['Alles van Pro', 'Gedeelde werkruimte', 'Ledenbeheer', 'API-toegang', 'SSO & SAML', 'SLA 99.9%', 'Toegewezen accountmanager'] }], faq: [{ q: 'Kan ik op elk moment opzeggen?', a: 'Ja. Geen verplichting. Annuleer met één klik vanuit de instellingen.' }, { q: 'Zijn mijn gegevens veilig?', a: 'Absoluut. End-to-end versleuteling, geen retentie na verwijdering.' }, { q: 'Is er een berichtenlimiet op Pro?', a: 'Nee. Berichten zijn onbeperkt op Pro.' }] },
  },


  pl: {
    nav: { features: 'Funkcje', pricing: 'Cennik', login: 'Zaloguj', start: 'Rozpocznij' },
    hero: { badge: 'Netral 1.3 — Ulepszone wyszukiwanie w sieci', title1: 'AI, które szuka', title2: 'zanim odpowie.', subtitle: 'Zadaj pytanie. Netral przeszukuje sieć, analizuje źródła i daje precyzyjną odpowiedź z weryfikowalnymi cytatami.', cta: 'Zacznij za darmo', login: 'Zaloguj', note: 'Za darmo • Bez karty • Gotowe w 10 sekund' },
    demo: { userMsg: 'Jakie są najnowsze osiągnięcia AI w tym tygodniu?', searching: 'Szukam…', response1: 'Oto główne postępy tego tygodnia:', response2: '— ulepszone wieloetapowe rozumowanie.', response3: '— bardziej stabilne autonomiczne agenty' },
    stats: { latency: 'Średnie opóźnienie', uptime: 'Dostępność', users: 'Aktywni użytkownicy' },
    features: { title: 'Zbudowane dla ciekawskich umysłów', subtitle: 'AI, które nie wymyśla. Wie, kiedy szukać. Cytuje swoje źródła.', seeAll: 'Zobacz wszystkie funkcje →', items: [{ title: 'Wyszukiwanie w sieci w czasie rzeczywistym', desc: 'Datowane, klikalne, weryfikowalne źródła.' }, { title: 'Zaawansowane rozumowanie', desc: 'Krok po kroku rozwiązywanie złożonych problemów.' }, { title: 'Naturalne rozmowy', desc: 'Jak rozmowa z zaufanym ekspertem.' }, { title: 'Natychmiastowy strumień', desc: 'Czytaj odpowiedź, gdy się tworzy.' }, { title: 'Wyszukiwanie semantyczne', desc: 'Rozumie znaczenie, nie tylko słowa kluczowe.' }, { title: 'Prywatne domyślnie', desc: 'Zaszyfrowane. Usuwalne. Nigdy nie używane do treningu.' }] },
    pricing: { title1: 'Za darmo na start.', title2: 'Pro gdy będziesz gotowy.', subtitle: '20 wiadomości/dzień za darmo. Pro dla nieograniczonego dostępu za 12€/miesiąc.', cta: 'Utwórz darmowe konto', seePricing: 'Zobacz cennik' },
    footer: { privacy: 'Prywatność', contact: 'Kontakt' },
    chat: { hello: 'Cześć', helloName: 'Cześć, {name}', howCanIHelp: 'Jak mogę ci dziś pomóc?', newConversation: 'Nowa rozmowa', search: 'Szukaj', noConversations: 'Brak rozmów', noResults: 'Brak wyników', today: 'Dzisiaj', yesterday: 'Wczoraj', last7days: 'Ostatnie 7 dni', last30days: 'Ostatnie 30 dni', older: 'Starsze', settings: 'Ustawienia', logout: 'Wyloguj', rename: 'Zmień nazwę', remix: 'Remix', delete: 'Usuń', deleteConfirm: 'Usunąć tę rozmowę?', searching: 'Szukam…', reading: 'Czytam źródła…', thinking: 'Myślę…', login: 'Zaloguj', loginTitle: 'Witaj ponownie', loginSubtitle: 'Zaloguj się na swoje konto', signupTitle: 'Utwórz konto', signupSubtitle: 'Za darmo, w mniej niż minutę', noAccount: 'Nie masz konta?', createOne: 'Utwórz', alreadyAccount: 'Już zarejestrowany?', signIn: 'Zaloguj się', createAccount: 'Utwórz moje konto' },
    vscodeAuth: { title: 'Netral Code', subtitle: 'Połącz swoje IDE z Netral', loginRequired: 'Wymagane logowanie', loginDesc: 'Zaloguj się, aby połączyć konto z VS Code.', confirmTitle: 'Połącz VS Code', confirmDesc: 'Zezwolić Netral Code na dostęp do konta?', authorize: 'Autoryzuj', tokenNote: 'Zostanie utworzony token API dla rozszerzenia VS Code.', success: 'Połączono!', successDesc: 'Wróć do VS Code. Rozszerzenie jest gotowe.', expired: 'Kod wygasł', expiredDesc: 'Wpisz /login w VS Code, aby spróbować ponownie.', error: 'Błąd' },
    featuresPage: { back: 'Wstecz', title: 'Funkcje', subtitle: 'Wszystko, czego potrzebujesz do niezawodnego, szybkiego i szanującego prywatność AI.', cta: 'Gotowy, żeby spróbować?', ctaDesc: 'Utwórz konto w 10 sekund. Za darmo, bez karty.', ctaBtn: 'Zacznij za darmo', items: FEAT_ITEMS_PL },
    pricingPage: { back: 'Wstecz', title1: 'Proste ceny,', title2: 'bez niespodzianek.', subtitle: 'Zacznij za darmo. Przejdź na Pro, gdy będziesz gotowy.', popular: 'Popularny', faqTitle: 'Często zadawane pytania', plans: [{ name: 'Darmowy', price: '0€', period: '/miesiąc', desc: 'Odkryj Netral bez zobowiązań.', cta: 'Zacznij', features: ['20 wiadomości dziennie', 'Podstawowe wyszukiwanie', '7 dni historii', '1 jednoczesna rozmowa'] }, { name: 'Pro', price: '12€', period: '/miesiąc', desc: 'Dla profesjonalistów i twórców.', cta: 'Przejdź na Pro', features: ['Nieograniczone wiadomości', 'Zaawansowane wyszukiwanie', 'Nieograniczona historia', 'Nieograniczone rozmowy', 'Model priorytetowy (GPT-4o)', 'Eksport rozmów', 'Priorytetowe wsparcie'] }, { name: 'Zespół', price: '29€', period: '/użytkownik/miesiąc', desc: 'Dla zespołów chcących współpracować.', cta: 'Skontaktuj się', features: ['Wszystko z Pro', 'Współdzielone środowisko', 'Zarządzanie członkami', 'Dostęp API', 'SSO & SAML', 'SLA 99.9%', 'Dedykowany opiekun'] }], faq: [{ q: 'Czy mogę anulować w dowolnym momencie?', a: 'Tak. Bez zobowiązań. Anuluj jednym kliknięciem z ustawień.' }, { q: 'Czy moje dane są bezpieczne?', a: 'Absolutnie. Szyfrowanie end-to-end, brak retencji po usunięciu.' }, { q: 'Czy w Pro jest limit wiadomości?', a: 'Nie. Wiadomości w Pro są nieograniczone.' }] },
  },
  uk: {
    nav: { features: 'Функції', pricing: 'Ціни', login: 'Увійти', start: 'Почати' },
    hero: { badge: 'Netral 1.3 — Покращений веб-пошук', title1: 'ШІ, що шукає', title2: 'перш ніж відповісти.', subtitle: 'Поставте питання. Netral шукає в мережі, аналізує джерела та дає точну відповідь із верифікованими посиланнями.', cta: 'Почати безкоштовно', login: 'Увійти', note: 'Безкоштовно • Без картки • Готово за 10 секунд' },
    demo: { userMsg: 'Які останні розробки у сфері ШІ цього тижня?', searching: 'Пошук…', response1: 'Ось основні досягнення цього тижня:', response2: '— покращене багатоетапне міркування.', response3: '— більш стабільні автономні агенти' },
    stats: { latency: 'Середня затримка', uptime: 'Доступність', users: 'Активні користувачі' },
    features: { title: 'Створено для допитливих розумів', subtitle: 'ШІ, який не вигадує. Знає, коли шукати. Цитує свої джерела.', seeAll: 'Всі функції →', items: [{ title: 'Пошук у реальному часі', desc: 'Джерела з датами, посиланнями, верифіковані.' }, { title: 'Розширені міркування', desc: 'Покрокове вирішення складних задач.' }, { title: 'Природні розмови', desc: 'Як розмова з надійним експертом.' }, { title: 'Миттєвий стрімінг', desc: 'Читайте відповідь, поки вона формується.' }, { title: 'Семантичний пошук', desc: 'Розуміє зміст, не лише ключові слова.' }, { title: 'Приватність за замовчуванням', desc: 'Зашифровано. Видаляється. Ніколи не використовується для навчання.' }] },
    pricing: { title1: 'Безкоштовно для початку.', title2: 'Pro коли будете готові.', subtitle: '20 повідомлень/день безкоштовно. Pro для необмеженого доступу за 12€/місяць.', cta: 'Створити безкоштовний акаунт', seePricing: 'Переглянути ціни' },
    footer: { privacy: 'Конфіденційність', contact: 'Контакти' },
    chat: { hello: 'Привіт', helloName: 'Привіт, {name}', howCanIHelp: 'Чим можу допомогти сьогодні?', newConversation: 'Нова розмова', search: 'Пошук', noConversations: 'Немає розмов', noResults: 'Немає результатів', today: 'Сьогодні', yesterday: 'Вчора', last7days: 'Останні 7 днів', last30days: 'Останні 30 днів', older: 'Старіше', settings: 'Налаштування', logout: 'Вийти', rename: 'Перейменувати', remix: 'Ремікс', delete: 'Видалити', deleteConfirm: 'Видалити цю розмову?', searching: 'Пошук…', reading: 'Читання джерел…', thinking: 'Роздумую…', login: 'Увійти', loginTitle: 'Ласкаво просимо', loginSubtitle: 'Увійдіть до свого акаунту', signupTitle: 'Створити акаунт', signupSubtitle: 'Безкоштовно, менше хвилини', noAccount: 'Немає акаунту?', createOne: 'Створити', alreadyAccount: 'Вже зареєстровані?', signIn: 'Увійти', createAccount: 'Створити акаунт' },
    vscodeAuth: { title: 'Netral Code', subtitle: 'Підключіть IDE до Netral', loginRequired: 'Потрібен вхід', loginDesc: 'Увійдіть, щоб пов\'язати акаунт з VS Code.', confirmTitle: 'Пов\'язати VS Code', confirmDesc: 'Дозволити Netral Code доступ до акаунту?', authorize: 'Авторизувати', tokenNote: 'Буде створено API-токен для розширення VS Code.', success: 'Підключено!', successDesc: 'Поверніться до VS Code. Розширення готове.', expired: 'Код прострочений', expiredDesc: 'Введіть /login у VS Code для повтору.', error: 'Помилка' },
    featuresPage: { back: 'Назад', title: 'Функції', subtitle: 'Все необхідне для надійного, швидкого та конфіденційного ШІ.', cta: 'Готові спробувати?', ctaDesc: 'Створіть акаунт за 10 секунд. Безкоштовно, без картки.', ctaBtn: 'Почати безкоштовно', items: FEAT_ITEMS_UK },
    pricingPage: { back: 'Назад', title1: 'Прості ціни,', title2: 'без сюрпризів.', subtitle: 'Почніть безкоштовно. Перейдіть на Pro, коли будете готові.', popular: 'Популярний', faqTitle: 'Часті запитання', plans: [{ name: 'Безкоштовно', price: '0€', period: '/місяць', desc: 'Відкрийте для себе Netral без зобов\'язань.', cta: 'Почати', features: ['20 повідомлень на день', 'Базовий веб-пошук', 'Історія 7 днів', '1 одночасна розмова'] }, { name: 'Pro', price: '12€', period: '/місяць', desc: 'Для професіоналів і творчих людей.', cta: 'Перейти на Pro', features: ['Необмежені повідомлення', 'Розширений пошук', 'Необмежена історія', 'Необмежені розмови', 'Пріоритетна модель (GPT-4o)', 'Експорт розмов', 'Пріоритетна підтримка'] }, { name: 'Команда', price: '29€', period: '/користувач/місяць', desc: 'Для команд, що хочуть співпрацювати.', cta: 'Зв\'язатися', features: ['Все з Pro', 'Спільний робочий простір', 'Управління учасниками', 'API доступ', 'SSO & SAML', 'SLA 99.9%', 'Виділений менеджер'] }], faq: [{ q: 'Чи можна скасувати в будь-який момент?', a: 'Так. Без зобов\'язань. Скасуйте одним кліком з налаштувань.' }, { q: 'Мої дані в безпеці?', a: 'Абсолютно. Наскрізне шифрування, без зберігання після видалення.' }, { q: 'Чи є ліміт повідомлень у Pro?', a: 'Ні. Повідомлення в Pro необмежені.' }] },
  },
}
